-- sound list comes from here:  https://pastebin.com/raw/0neZdsZ5

local isVisible = false
local loaded = false
local nativeCalled = ''

local soundsFrontend = {
    --[[
    NOTE:   Looks like the sounds I commented out 
            cannot be played with lua, or at least
            I have no idea how to go about doing that.
    --]]
    { -1, '10s', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { -1, '1st_Person_Transition', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 0 },
    { -1, '1st_Person_Transition', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { -1, '3_2_1', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, '3_2_1', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, '3_2_1_NON_RACE', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, '5_SEC_WARNING', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, '5_Second_Timer', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 0 },
    { -1, '5s', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { -1, '5s_To_Event_Start_Countdown', 'GTAO_FM_Events_Soundset', 0 },
    --[[
    { -1, 'ADD_SPAWN_POINT', sub_1b14d(), 1 },
    { -1, 'ADD_SPAWN_POINT', sub_3d184(), 1 },
    { -1, 'ADD_SPAWN_POINT', sub_3e7f3(), 1 },
    --]]
    { -1, 'Airhorn', 'DLC_TG_Running_Back_Sounds', 0 },
    { -1, 'Apt_Style_Purchase', 'DLC_APT_Apartment_SoundSet', 0 },
    { -1, 'ARM_3_CAR_GLASS_CRASH', 0, 1 },
    { -1, 'ARM_3_PISTOL_COCK', 0, 1 },
    { -1, 'ARM_WRESTLING_WHOOSH_MASTER', 0, 1 },
    { -1, 'Arming_Countdown', 'GTAO_Speed_Convoy_Soundset', 0 },
    { -1, 'ASSASSINATIONS_HOTEL_TIMER_COUNTDOWN', 'ASSASSINATION_MULTI', 1 },
    { -1, 'ATM_WINDOW', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'BACK', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'BACK', 'HUD_FREEMODE_SOUNDSET', 1 },
    { -1, 'BACK', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'BACK', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'BACK', 'HUD_FRONTEND_MP_SOUNDSET', 1 },
    { -1, 'BACK', 'HUD_FRONTEND_TATTOO_SHOP_SOUNDSET', 1 },
    { -1, 'BACK', 'HUD_MINI_GAME_SOUNDSET', 1 },
    --[[
    { -1, 'BACK', sub_240d0(), 1 },
    { -1, 'BACK', sub_46181(), 1 },
    { -1, 'BACK', sub_474a9(), 1 },
    { -1, 'BACK', sub_a1df9(), 1 },
    { -1, 'BACK', sub_d0c84(), 1 },
    --]]
    { -1, 'Banshee2_Upgrade', 'JA16_Super_Mod_Garage_Sounds', 1 },
    { -1, 'BASE_JUMP_PASSED', 'HUD_AWARDS', 1 },
    { -1, 'Beast_Checkpoint', 'APT_BvS_Soundset', 0 },
    { -1, 'Beast_Checkpoint_NPC', 'APT_BvS_Soundset', 0 },
    { -1, 'Bed', 'WastedSounds', 1 },
    -- { -1, 'Bed', l_6A, 1 },
    { -1, 'Beep_Green', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'Beep_Red', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'Blade_Appear', 'APT_BvS_Soundset', 0 },
    { -1, 'BOATS_PLANES_HELIS_BOOM', 'MP_LOBBY_SOUNDS', 1 },
    { -1, 'Bomb_Disarmed', 'GTAO_Speed_Convoy_Soundset', 0 },
    { -1, 'Boss_Blipped', 'GTAO_Magnate_Hunt_Boss_SoundSet', 0 },
    { -1, 'Boss_Message_Orange', 'GTAO_Boss_Goons_FM_Soundset', 0 },
    { -1, 'Breaker_01', 'DLC_HALLOWEEN_FVJ_Sounds', 0 },
    { -1, 'Breaker_02', 'DLC_HALLOWEEN_FVJ_Sounds', 0 },
    { -1, 'BULL_SHARK_TESTOSTERONE_END_MASTER', '', 0 },
    { -1, 'BULL_SHARK_TESTOSTERONE_START_MASTER', '', 0 },
    { -1, 'Bus_Schedule_Pickup', 'DLC_PRISON_BREAK_HEIST_SOUNDS', 0 },
    { -1, 'CABLE_SNAPS', 'CONSTRUCTION_ACCIDENT_1_SOUNDS', 1 },
    { -1, 'CAM_PAN_DARTS', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'Camera_Shoot', 'Phone_Soundset_Franklin', 1 },
    -- { -1, 'Camera_Shoot', &g_3842, 1 },
    { -1, 'CANCEL', 'HUD_FREEMODE_SOUNDSET', 1 },
    { -1, 'CANCEL', 'HUD_FRONTEND_CLOTHESSHOP_SOUNDSET', 1 },
    { -1, 'CANCEL', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'CANCEL', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'CANCEL', 'HUD_LIQUOR_STORE_SOUNDSET', 1 },
    { -1, 'CANCEL', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'CAR_BIKE_WHOOSH', 'MP_LOBBY_SOUNDS', 1 },
    { -1, 'CHALLENGE_UNLOCKED', 'HUD_AWARDS', 1 },
    { -1, 'CHARACTER_SELECT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'CHECKPOINT_AHEAD', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, 'Checkpoint_Beast_Hit', 'FM_Events_Sasquatch_Sounds', 0 },
    { -1, 'CHECKPOINT_BEHIND', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, 'Checkpoint_Cash_Hit', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Checkpoint_Hit', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'CHECKPOINT_MISSED', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, 'CHECKPOINT_NORMAL', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, 'CHECKPOINT_PERFECT', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, 'Checkpoint_Teammate', 'GTAO_Shepherd_Sounds', 0 },
    { -1, 'CHECKPOINT_UNDER_THE_BRIDGE', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, 'Cheers', 'DLC_TG_Running_Back_Sounds', 0 },
    { -1, 'Click', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'CLICK_BACK', 'WEB_NAVIGATION_SOUNDS_PHONE', 1 },
    { -1, 'Click_Fail', 'WEB_NAVIGATION_SOUNDS_PHONE', 1 },
    { -1, 'Click_Special', ' WEB_NAVIGATION_SOUNDS_PHONE', 1 },
    { -1, 'Click_Special', 'WEB_NAVIGATION_SOUNDS_PHONE', 1 },
    { -1, 'CLOSE_WINDOW', 'LESTER1A_SOUNDS', 1 },
    { -1, 'CLOSED', 'DLC_APT_YACHT_DOOR_SOUNDS', 1 },
    { -1, 'CLOSED', 'MP_PROPERTIES_ELEVATOR_DOORS', 1 },
    { -1, 'COMPUTERS_MOUSE_CLICK', 0, 1 },
    { -1, 'CONFIRM_BEEP', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'CONTINUE', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'CONTINUE', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Continue_Accepted', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Continue_Appears', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Crash', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'Criminal_Damage_High_Value', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Criminal_Damage_Kill_Player', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Criminal_Damage_Low_Value', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'CUTSCENE_DIALOGUE_OVERRIDE_SOUND_01', 0, 0 },
    { -1, 'CUTSCENE_DIALOGUE_OVERRIDE_SOUND_02', 0, 0 },
    { -1, 'Cycle_Item', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { -1, 'DELETE', 'HUD_DEATHMATCH_SOUNDSET', 1 },
    --[[
    { -1, 'DELETE', sub_1b14d(), 1 },
    { -1, 'DELETE', sub_3d184(), 1 },
    { -1, 'DELETE', sub_3e7f3(), 1 },
    { -1, 'DELETE', sub_d083a(), 1 },
    --]]
    { -1, 'Delete_Placed_Prop', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { -1, 'Deliver_Pick_Up', 'HUD_FRONTEND_MP_COLLECTABLE_SOUNDS', 1 },
    { -1, 'DiggerRevOneShot', 'BulldozerDefault', 1 },
    { -1, 'Door_Open', 'DOCKS_HEIST_FINALE_2B_SOUNDS', 1 },
    { -1, 'Drill_Pin_Break', 'DLC_HEIST_FLEECA_SOUNDSET', 1 },
    { -1, 'Dropped', 'HUD_FRONTEND_MP_COLLECTABLE_SOUNDS', 1 },
    { -1, 'DRUG_TRAFFIC_AIR_BOMB_DROP_ERROR_MASTER', 0, 1 },
    { -1, 'DRUG_TRAFFIC_AIR_SCREAMS', 0, 1 },
    { -1, 'EDIT', 'HUD_DEATHMATCH_SOUNDSET', 1 },
    --[[
    { -1, 'EDIT', sub_1b14d(), 1 },
    { -1, 'EDIT', sub_3d184(), 1 },
    { -1, 'EDIT', sub_3e7f3(), 1 },
    { -1, 'EDIT', sub_d083a(), 1 },
    --]]
    { -1, 'End_Squelch', 'CB_RADIO_SFX', 1 },
    { -1, 'Enemy_Capture_Start', 'GTAO_Magnate_Yacht_Attack_Soundset', 0 },
    { -1, 'Enemy_Deliver', 'HUD_FRONTEND_MP_COLLECTABLE_SOUNDS', 1 },
    { -1, 'Enemy_Pick_Up', 'HUD_FRONTEND_MP_COLLECTABLE_SOUNDS', 1 },
    { -1, 'Enter_1st', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Enter_1st', 'GTAO_Magnate_Boss_Modes_Soundset', 0 },
    { -1, 'Enter_Area', 'DLC_Lowrider_Relay_Race_Sounds', 0 },
    { -1, 'Enter_Capture_Zone', 'DLC_Apartments_Drop_Zone_Sounds', 0 },
    { -1, 'ERROR', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'ERROR', 'HUD_FRONTEND_CLOTHESSHOP_SOUNDSET', 1 },
    { -1, 'ERROR', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'ERROR', 'HUD_FRONTEND_TATTOO_SHOP_SOUNDSET', 1 },
    { -1, 'ERROR', 'HUD_LIQUOR_STORE_SOUNDSET', 1 },
    --[[
    { -1, 'ERROR', sub_240d0(), 1 },
    { -1, 'ERROR', sub_46181(), 1 },
    { -1, 'ERROR', sub_474a9(), 1 },
    { -1, 'ERROR', sub_a1df9(), 1 },
    { -1, 'ERROR', sub_d0c84(), 1 },
    --]]
    { -1, 'Event_Message_Purple', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Event_Start_Text', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'EXILE_3_TRAIN_BRAKE_PULL_MASTER', 0, 1 },
    { -1, 'EXILE_3_TRAIN_BRAKE_RELEASE_MASTER', 0, 1 },
    { -1, 'EXIT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Exit_Capture_Zone', 'DLC_Apartments_Drop_Zone_Sounds', 0 },
    { -1, 'Failure', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'Falling_Crates', 'EXILE_1', 1 },
    { -1, 'FAMILY_1_CAR_BREAKDOWN', 'FAMILY1_BOAT', 1 },
    { -1, 'FAMILY_1_CAR_BREAKDOWN_ADDITIONAL', 'FAMILY1_BOAT', 1 },
    { -1, 'Faster_Bar_Full', 'RESPAWN_ONLINE_SOUNDSET', 1 },
    { -1, 'Faster_Click', 'RESPAWN_ONLINE_SOUNDSET', 1 },
    { -1, 'FestiveGift', 'Feed_Message_Sounds', 0 },
    { -1, 'FIRST_PLACE', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'FLIGHT_SCHOOL_LESSON_PASSED', 'HUD_AWARDS', 1 },
    { -1, 'FLYING_STREAM_END_INSTANT', 'FAMILY_5_SOUNDS', 1 },
    { -1, 'FocusIn', 'HintCamSounds', 1 },
    { -1, 'FocusOut', 'HintCamSounds', 1 },
    { -1, 'Friend_Deliver', 'HUD_FRONTEND_MP_COLLECTABLE_SOUNDS', 1 },
    { -1, 'Friend_Pick_Up', 'HUD_FRONTEND_MP_COLLECTABLE_SOUNDS', 0 },
    { -1, 'Friend_Pick_Up', 'HUD_FRONTEND_MP_COLLECTABLE_SOUNDS', 1 },
    { -1, 'Frontend_Beast_Fade_Screen', 'FM_Events_Sasquatch_Sounds', 0 },
    { -1, 'Frontend_Beast_Freeze_Screen', 'FM_Events_Sasquatch_Sounds', 0 },
    { -1, 'Frontend_Beast_Text_Hit', 'FM_Events_Sasquatch_Sounds', 0 },
    { -1, 'Frontend_Beast_Transform_Back', 'FM_Events_Sasquatch_Sounds', 0 },
    { -1, 'GO', 'HUD_MINI_GAME_SOUNDSET', 0 },
    { -1, 'GO', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'GO_NON_RACE', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'Goal', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'GOLF_BIRDIE', 'HUD_AWARDS', 1 },
    { -1, 'GOLF_EAGLE', 'HUD_AWARDS', 1 },
    { -1, 'GOLF_HUD_HOLE_IN_ONE_MASTER', 0, 1 },
    { -1, 'GOLF_HUD_SCORECARD_MASTER', 0, 1 },
    { -1, 'GOLF_NEW_RECORD', 'HUD_AWARDS', 1 },
    { -1, 'Goon_Paid_Small', 'GTAO_Boss_Goons_FM_Soundset', 0 },
    { -1, 'Grab_Parachute', 'BASEJUMPS_SOUNDS', 1 },
    { -1, 'Hack_Failed', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 0 },
    { -1, 'Hack_Success', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 1 },
    { -1, 'HACKING_CLICK', 0, 1 },
    { -1, 'HACKING_CLICK_BAD', 0, 1 },
    { -1, 'HACKING_CLICK_GOOD', 0, 1 },
    { -1, 'HACKING_FAILURE', 0, 1 },
    { -1, 'HACKING_MOVE_CURSOR', 0, 1 },
    { -1, 'HACKING_SUCCESS', 0, 1 },
    { -1, 'Hang_Up', 'Phone_SoundSet_Michael', 1 },
    -- { -1, 'Hang_Up', &g_3842, 1 },
    { -1, 'HIGHLIGHT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Highlight_Accept', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Highlight_Cancel', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Highlight_Error', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Highlight_Move', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'HIGHLIGHT_NAV_UP_DOWN', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Hit', 'RESPAWN_ONLINE_SOUNDSET', 1 },
    { -1, 'Hit', 'RESPAWN_SOUNDSET', 0 },
    { -1, 'Hit', 'RESPAWN_SOUNDSET', 1 },
    { -1, 'Hit_1', 'LONG_PLAYER_SWITCH_SOUNDS', 0 },
    { -1, 'Hit_1', 'LONG_PLAYER_SWITCH_SOUNDS', 1 },
    { -1, 'Hit_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { -1, 'Hit_Out', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { -1, 'HOORAY', 'BARRY_02_SOUNDSET', 1 },
    { -1, 'HORDE_COOL_DOWN_TIMER', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'HUD_FREEMODE_CANCEL_MASTER', 0, 1 },
    { -1, 'Kill_List_Counter', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'LAMAR1_PARTYGIRLS_master', 0, 1 },
    { -1, 'LEADER_BOARD', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'LEADERBOARD', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'Lester_Laugh_Phone', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'Lights_On', 'GTAO_MUGSHOT_ROOM_SOUNDS', 1 },
    { -1, 'LIMIT', 'DLC_APT_YACHT_DOOR_SOUNDS', 1 },
    { -1, 'LIMIT', 'GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS', 1 },
    { -1, 'LIMIT', 'GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS', 1 },
    { -1, 'Load_Scene', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { -1, 'LOCAL_PLYR_CASH_COUNTER_COMPLETE', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 0 },
    { -1, 'LOCAL_PLYR_CASH_COUNTER_INCREASE', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 0 },
    { -1, 'LOOSE_MATCH', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'Lose_1st', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Lose_1st', 'GTAO_Magnate_Boss_Modes_Soundset', 0 },
    { -1, 'LOSER', 'HUD_AWARDS', 1 },
    { -1, 'Lowrider_Upgrade', 'Lowrider_Super_Mod_Garage_Sounds', 1 },
    { -1, 'Map_Roll_Down', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Map_Roll_Up', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'MARKER_ERASE', 'HEIST_BULLETIN_BOARD_SOUNDSET', 1 },
    { -1, 'MARTIN1_DISTANT_TRAIN_HORNS_MASTER', 0, 1 },
    { -1, 'MEDAL_BRONZE', 'HUD_AWARDS', 1 },
    { -1, 'MEDAL_GOLD', 'HUD_AWARDS', 1 },
    { -1, 'MEDAL_SILVER', 'HUD_AWARDS', 1 },
    { -1, 'MEDAL_UP', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'Menu_Accept', 'Phone_SoundSet_Default', 1 },
    --[[
    { -1, 'Menu_Accept', &g_3842, 1 },
    { -1, 'Menu_Back', &g_3842, 1 },
    { -1, 'Menu_Navigate', &g_3842, 1 },
    --]]
    { -1, 'MICHAEL_LONG_SCREAM', 'FAMILY_5_SOUNDS', 1 },
    { -1, 'MICHAEL_SOFA_REMOTE_CLICK_VOLUME_MASTER', 0, 1 },
    { -1, 'MICHAEL_SOFA_TV_CHANGE_CHANNEL_MASTER', 0, 1 },
    { -1, 'MICHAEL_SOFA_TV_ON_MASTER', 0, 1 },
    { -1, 'Mission_Pass_Notify', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 0 },
    { -1, 'Mission_Pass_Notify', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 1 },
    { -1, 'MP_5_SECOND_TIMER', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'MP_AWARD', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'MP_Flash', 'WastedSounds', 1 },
    { -1, 'MP_IDLE_KICK', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'MP_IDLE_TIMER', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'MP_Impact', 'WastedSounds', 1 },
    { -1, 'MP_RANK_UP', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'MP_WAVE_COMPLETE', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'NAV', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'Nav_Arrow_Ahead', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 1 },
    { -1, 'Nav_Arrow_Behind', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 1 },
    { -1, 'Nav_Arrow_Left', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 1 },
    { -1, 'Nav_Arrow_Right', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 1 },
    { -1, 'NAV_LEFT_RIGHT', 'HUD_FREEMODE_SOUNDSET', 1 },
    { -1, 'NAV_LEFT_RIGHT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'NAV_LEFT_RIGHT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'NAV_UP_DOWN', 'HUD_FREEMODE_SOUNDSET', 1 },
    { -1, 'NAV_UP_DOWN', 'HUD_FRONTEND_CLOTHESSHOP_SOUNDSET', 1 },
    { -1, 'NAV_UP_DOWN', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'NAV_UP_DOWN', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'NAV_UP_DOWN', 'HUD_FRONTEND_TATTOO_SHOP_SOUNDSET', 1 },
    { -1, 'NAV_UP_DOWN', 'HUD_LIQUOR_STORE_SOUNDSET', 1 },
    { -1, 'NAV_UP_DOWN', 'HUD_MINI_GAME_SOUNDSET', 1 },
    --[[
    { -1, 'NAV_UP_DOWN', sub_240d0(), 1 },
    { -1, 'NAV_UP_DOWN', sub_46181(), 1 },
    { -1, 'NAV_UP_DOWN', sub_474a9(), 1 },
    { -1, 'NAV_UP_DOWN', sub_a1df9(), 1 },
    { -1, 'NAV_UP_DOWN', sub_d0c84(), 1 },
    --]]
    { -1, 'Near_Miss_Counter_Reset', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'NET_RACE_START_EVENT_MASTER', 0, 1 },
    { -1, 'NO', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    -- { -1, 'Notification', &g_3842, 1 },
    { -1, 'Object_Collect_Player', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Object_Collect_Remote', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Object_Dropped_Remote', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'OFF', v_4, 1 },
    { -1, 'Off_High', 'MP_RADIO_SFX', 1 },
    { -1, 'OK', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'ON', 'NOIR_FILTER_SOUNDS', 1 },
    -- { -1, 'ON', v_4, 1 },
    { -1, 'On_Call_Player_Join', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 1 },
    { -1, 'Oneshot_Final', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { -1, 'OOB_Cancel', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'OOB_Start', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'OPEN_WINDOW', 'LESTER1A_SOUNDS', 1 },
    { -1, 'OPENED', 'MP_PROPERTIES_ELEVATOR_DOORS', 1 },
    { -1, 'OTHER_TEXT', 'HUD_AWARDS', 1 },
    { -1, 'Out_Of_Area', 'DLC_Lowrider_Relay_Race_Sounds', 0 },
    { -1, 'Paper_Shuffle', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Parcel_Vehicle_Lost', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'Payment_Non_Player', 'DLC_HEISTS_GENERIC_SOUNDS', 0 },
    { -1, 'Payment_Player', 'DLC_HEISTS_GENERIC_SOUNDS', 0 },
    { -1, 'Pen_Tick', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'PERSON_SCROLL', 'HEIST_BULLETIN_BOARD_SOUNDSET', 1 },
    { -1, 'PERSON_SELECT', 'HEIST_BULLETIN_BOARD_SOUNDSET', 1 },
    { -1, 'Phone_Generic_Key_02', 'HUD_MINIGAME_SOUNDSET', 1 },
    { -1, 'Phone_Generic_Key_03', 'HUD_MINIGAME_SOUNDSET', 1 },
    { -1, 'PICK_UP', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'PICK_UP_WEAPON', 'HUD_FRONTEND_CUSTOM_SOUNDSET', 1 },
    { -1, 'PICKUP_WEAPON_SMOKEGRENADE', 'HUD_FRONTEND_WEAPONS_PICKUPS_SOUNDSET', 1 },
    { -1, 'Pin_Bad', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 1 },
    { -1, 'PIN_BUTTON', 'ATM_SOUNDS', 1 },
    { -1, 'Pin_Centred', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 1 },
    { -1, 'Pin_Good', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 1 },
    { -1, 'PIPES_LAND', 'CONSTRUCTION_ACCIDENT_1_SOUNDS', 1 },
    --[[
    { -1, 'PLACE_CHECKPOINT', sub_d083a(), 1 },
    { -1, 'PLACE_ENEMY', sub_3d184(), 1 },
    { -1, 'PLACE_ENEMY', sub_3e7f3(), 1 },
    { -1, 'PLACE_OBJECT', sub_3d184(), 1 },
    { -1, 'PLACE_OBJECT', sub_3e7f3(), 1 },
    --]]
    { -1, 'Place_Prop_Fail', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { -1, 'Place_Prop_Success', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    --[[
    { -1, 'PLACE_VEHICLE', sub_1b14d(), 1 },
    { -1, 'PLACE_VEHICLE', sub_3d184(), 1 },
    { -1, 'PLACE_VEHICLE', sub_3e7f3(), 1 },
    --]]
    { -1, 'Player_Collect', 'DLC_PILOT_MP_HUD_SOUNDS', 0 },
    { -1, 'Player_Enter_Line', 'GTAO_FM_Cross_The_Line_Soundset', 0 },
    { -1, 'Player_Exit_Line', 'GTAO_FM_Cross_The_Line_Soundset', 0 },
    { -1, 'Power_Down', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'Pre_Screen_Stinger', 'DLC_HEISTS_FAILED_SCREEN_SOUNDS', 0 },
    { -1, 'Pre_Screen_Stinger', 'DLC_HEISTS_FINALE_SCREEN_SOUNDS', 0 },
    { -1, 'Pre_Screen_Stinger', 'DLC_HEISTS_FINALE_SCREEN_SOUNDS', 1 },
    { -1, 'Pre_Screen_Stinger', 'DLC_HEISTS_PREP_SCREEN_SOUNDS', 0 },
    { -1, 'Pre_Screen_Stinger', 'DLC_HEISTS_PREP_SCREEN_SOUNDS', 1 },
    { -1, 'PROPERTY_PURCHASE', 'HUD_AWARDS', 1 },
    { -1, 'PROPERTY_PURCHASE_MEDIUM', 'HUD_PROPERTY_SOUNDSET', 1 },
    { -1, 'PS2A_DISTANT_TRAIN_HORNS_MASTER', 0, 1 },
    { -1, 'PS2A_MONEY_LOST', 'PALETO_SCORE_2A_BANK_SS', 1 },
    -- { -1, 'Pull_Out', &g_3842, 1 },
    { -1, 'PURCHASE', 'HUD_FRONTEND_TATTOO_SHOP_SOUNDSET', 1 },
    { -1, 'PURCHASE', 'HUD_LIQUOR_STORE_SOUNDSET', 1 },
    { -1, 'PUSH', 'DLC_APT_YACHT_DOOR_SOUNDS', 1 },
    { -1, 'PUSH', 'GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS', 1 },
    { -1, 'PUSH', 'GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS', 1 },
    { -1, 'Put_Away', 'Phone_SoundSet_Michael', 1 },
    -- { -1, 'Put_Away', &g_3842, 1 },
    { -1, 'QUIT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'QUIT_WHOOSH', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'RACE_PLACED', 'HUD_AWARDS', 1 },
    { -1, 'Radar_Beast_Blip', 'FM_Events_Sasquatch_Sounds', 0 },
    { -1, 'RAMP_DOWN', 'TRUCK_RAMP_DOWN', 1 },
    { -1, 'RAMP_UP', 'TRUCK_RAMP_DOWN', 1 },
    { -1, 'RAMPAGE_KILLED_COUNTER_MASTER', 0, 1 },
    { -1, 'RAMPAGE_KILLED_HEAD_SHOT_MASTER', 0, 1 },
    { -1, 'RAMPAGE_PASSED_MASTER', 0, 1 },
    { -1, 'RAMPAGE_ROAR_MASTER', 0, 1 },
    { -1, 'RANK_UP', 'HUD_AWARDS', 1 },
    { -1, 'REMOTE_PLYR_CASH_COUNTER_COMPLETE', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 0 },
    { -1, 'REMOTE_PLYR_CASH_COUNTER_INCREASE', 'DLC_HEISTS_GENERAL_FRONTEND_SOUNDS', 0 },
    { -1, 'Remote_Sniper_Rifle_Fire', 0, 1 },
    { -1, 'Reset_Prop_Position', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { -1, 'RESTART', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'RETRY', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Retune_High', 'MP_RADIO_SFX', 1 },
    { -1, 'ROBBERY_MONEY_TOTAL', 'HUD_FRONTEND_CUSTOM_SOUNDSET', 1 },
    { -1, 'ROPE_CUT', 'ROPE_CUT_SOUNDSET', 1 },
    { -1, 'ROUND_ENDING_STINGER_CUSTOM', 'CELEBRATION_SOUNDSET', 0 },
    { -1, 'Save_Scene', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { -1, 'SCOPE_UI_MASTER', 0, 1 },
    { -1, 'SCREEN_FLASH', 'CELEBRATION_SOUNDSET', 1 },
    { -1, 'ScreenFlash', 'MissionFailedSounds', 1 },
    { -1, 'ScreenFlash', 'WastedSounds', 1 },
    -- { -1, 'ScreenFlash', l_6A, 1 },
    { -1, 'SELECT', 'HUD_FREEMODE_SOUNDSET', 1 },
    { -1, 'SELECT', 'HUD_FRONTEND_CLOTHESSHOP_SOUNDSET', 1 },
    { -1, 'SELECT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'SELECT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'SELECT', 'HUD_FRONTEND_MP_SOUNDSET', 0 },
    { -1, 'SELECT', 'HUD_FRONTEND_MP_SOUNDSET', 1 },
    { -1, 'SELECT', 'HUD_FRONTEND_TATTOO_SHOP_SOUNDSET', 1 },
    { -1, 'SELECT', 'HUD_LIQUOR_STORE_SOUNDSET', 1 },
    { -1, 'SELECT', 'HUD_MINI_GAME_SOUNDSET', 1 },
    --[[
    { -1, 'SELECT', sub_240d0(), 1 },
    { -1, 'SELECT', sub_46181(), 1 },
    { -1, 'SELECT', sub_474a9(), 1 },
    { -1, 'SELECT', sub_a1df9(), 1 },
    { -1, 'SELECT', sub_d0c84(), 1 },
    { -1, 'SELECT_LOCATION', sub_1b14d(), 1 },
    { -1, 'SELECT_LOCATION', sub_3d184(), 1 },
    { -1, 'SELECT_LOCATION', sub_3e7f3(), 1 },
    { -1, 'SELECT_LOCATION', sub_d083a(), 1 },
    --]]
    { -1, 'Select_Placed_Prop', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    -- { -1, 'SELECT_START_GRID_POSITION', sub_d083a(), 1 },
    { -1, 'Shard_Disappear', 'GTAO_Boss_Goons_FM_Shard_Sounds', 0 },
    { -1, 'Shard_Disappear', 'GTAO_FM_Events_Soundset', 0 },
    { -1, 'SHOOTING_RANGE_ROUND_OVER', 'HUD_AWARDS', 1 },
    { -1, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { -1, 'Short_Transition_Out', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { -1, 'SKIP', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Start', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'Start_Squelch', 'CB_RADIO_SFX', 1 },
    { -1, 'STUN_COLLECT', 'MINUTE_MAN_01_SOUNDSET', 1 },
    { -1, 'Success', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'SultanRS_Upgrade', 'JA16_Super_Mod_Garage_Sounds', 1 },
    { -1, 'Swap_Sides', 'DLC_HALLOWEEN_FVJ_Sounds', 0 },
    { -1, 'SWING_SHUT', 'GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS', 1 },
    { -1, 'SWING_SHUT', 'GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS', 1 },
    { -1, 'Tattooing_Oneshot', 'TATTOOIST_SOUNDS', 1 },
    { -1, 'Tattooing_Oneshot_Remove', 'TATTOOIST_SOUNDS', 1 },
    { -1, 'Team_Capture_Start', 'GTAO_Magnate_Yacht_Attack_Soundset', 0 },
    { -1, 'TENNIS_MATCH_POINT', 'HUD_AWARDS', 1 },
    { -1, 'TENNIS_POINT_WON', 'HUD_AWARDS', 1 },
    --{ -1, 'Text_Arrive_Tone', &g_3842, 1 },
    { -1, 'TextHit', 'WastedSounds', 1 },
    --{ -1, 'TextHit', l_6A, 1 },
    { -1, 'Thermal_Off', 'CAR_STEAL_2_SOUNDSET', 1 },
    { -1, 'Thermal_On', 'CAR_STEAL_2_SOUNDSET', 1 },
    { -1, 'THERMAL_VISION_GOGGLES_OFF_MASTER', 0, 0 },
    { -1, 'THERMAL_VISION_GOGGLES_OFF_MASTER', 0, 1 },
    { -1, 'THERMAL_VISION_GOGGLES_ON_MASTER', 0, 1 },
    { -1, 'TIME_LAPSE_MASTER', 0, 1 },
    { -1, 'TIMER', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Timer_10s', 'DLC_HALLOWEEN_FVJ_Sounds', 0 },
    { -1, 'TIMER_STOP', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, 'TOGGLE_ON', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'TOGGLE_ON', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Traffic_Control_Fail', 'BIG_SCORE_3A_SOUNDS', 1 },
    { -1, 'Traffic_Control_Fail_Blank', 'BIG_SCORE_3A_SOUNDS', 1 },
    { -1, 'Traffic_Control_Light_Switch_Back', 'BIG_SCORE_3A_SOUNDS', 1 },
    { -1, 'TRAFFIC_CONTROL_MOVE_CROSSHAIR', 'BIG_SCORE_3A_SOUNDS', 1 },
    { -1, 'Turn', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { -1, 'UNDER_THE_BRIDGE', 'HUD_AWARDS', 1 },
    { -1, 'UNDER_WATER_COME_UP', 0, 1 },
    { -1, 'UNDO', 'HEIST_BULLETIN_BOARD_SOUNDSET', 1 },
    { -1, 'WAYPOINT_SET', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0 },
    { -1, 'WEAKEN', 'CONSTRUCTION_ACCIDENT_1_SOUNDS', 1 },
    { -1, 'WEAPON_AMMO_PURCHASE', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_ATTACHMENT_EQUIP', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_ATTACHMENT_UNEQUIP', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_PURCHASE', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_ARMOR', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_BATON', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_FUEL_CAN', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_GRENADE_LAUNCHER', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_HANDGUN', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_KNIFE', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_OTHER', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_PARACHUTE', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_RIFLE', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_RPG_LAUNCHER', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'WEAPON_SELECT_SHOTGUN', 'HUD_AMMO_SHOP_SOUNDSET', 1 },
    { -1, 'Whistle', 'DLC_TG_Running_Back_Sounds', 0 },
    { -1, 'Whoosh_1s_L_to_R', 'MP_LOBBY_SOUNDS', 1 },
    { -1, 'Whoosh_1s_R_to_L', 'MP_LOBBY_SOUNDS', 1 },
    { -1, 'WIN', 'HUD_AWARDS', 1 },
    { -1, 'WOODEN_DOOR_CLOSED_AT', 0, 0 },
    { -1, 'WOODEN_DOOR_CLOSED_AT', 0, 1 },
    { -1, 'WOODEN_DOOR_CLOSING_AT', 0, 0 },
    { -1, 'WOODEN_DOOR_CLOSING_AT', 0, 1 },
    { -1, 'WOODEN_DOOR_OPEN_HANDLE_AT', 0, 0 },
    { -1, 'WOODEN_DOOR_OPEN_HANDLE_AT', 0, 1 },
    { -1, 'WOODEN_DOOR_OPEN_NO_HANDLE_AT', 0, 1 },
    { -1, 'YES', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, 'Zone_Enemy_Capture', 'DLC_Apartments_Drop_Zone_Sounds', 0 },
    { -1, 'Zone_Neutral', 'DLC_Apartments_Drop_Zone_Sounds', 0 },
    { -1, 'Zone_Team_Capture', 'DLC_Apartments_Drop_Zone_Sounds', 0 },
    { -1, 'Zoom_In', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Zoom_Left', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Zoom_Out', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    { -1, 'Zoom_Right', 'DLC_HEIST_PLANNING_BOARD_SOUNDS', 1 },
    --[[
    { -1, a_0, 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { -1, a_0, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, a_1._f1C, a_1._f1B, 0 },
    { -1, a_1._f1D, a_1._f1B, 0 },
    { -1, l_2A7, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_3C, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_3D, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_3E, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_574, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_63, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_64, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_65, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_91F, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, l_920, 'HUD_MINI_GAME_SOUNDSET', 1 },
    { -1, sub_350f2(v_411, 'WIN', 'LOSER'), 'HUD_AWARDS', 1 },
    { -1, sub_4e10c(), sub_3d184(), 1 },
    { -1, sub_4f79c(), sub_3e7f3(), 1 },
    { -1, sub_821e3(a_1, a_3._f21), 'MP_RADIO_SFX', 1 },
    { -1, sub_8226b(a_1, a_3._f21), 'MP_RADIO_SFX', 1 },
    { -1, sub_826e4(a_1, a_3._f21), 'MP_RADIO_SFX', 1 },
    { -1, sub_936c5(a_0), 'HUD_PROPERTY_SOUNDSET', 1 },
    { -1, sub_a4b43(), sub_1b14d(), 1 },
    { -1, sub_d5ce9(), sub_d083a(), 1 },
    { -1, sub_d71cc(a_1, a_3._f21), 'MP_RADIO_SFX', 1 },
    { -1, sub_d7254(a_1, a_3._f21), 'MP_RADIO_SFX', 1 },
    { -1, sub_d76d5(a_1, a_3._f21), 'MP_RADIO_SFX', 1 },
    { -1, v_2A, v_29, 0 },
    { -1, v_9, v_B, 1 },
    { -1, v_A, v_B, 1 },
    { -1, v_C, 0, 1 },
    { a_0, 'CHECKPOINT_MISSED', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { a_0, 'CHECKPOINT_NORMAL', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { a_0._f1A1, 'Knuckle_Crack_Hard_Cel', 'MP_SNACKS_SOUNDSET', 1 },
    { a_0._f1A1, 'Knuckle_Crack_Slap_Cel', 'MP_SNACKS_SOUNDSET', 1 },
    { a_0._f1A1, 'Slow_Clap_Cel', 'MP_SNACKS_SOUNDSET', 1 },
    { a_0._f1D8, 'COP_HELI_CAM_ZOOM', 0, 1 },
    { a_0._f1D9, 'COP_HELI_CAM_TURN', 0, 1 },
    { a_0._f1DA, 'COP_HELI_CAM_BLEEP', 0, 1 },
    { a_0._f1DB, 'COP_HELI_CAM_BACKGROUND', 0, 1 },
    { a_0._f1DC, 'COP_HELI_CAM_SCAN_PED_LOOP', 0, 1 },
    { a_0._f1DD, 'COP_HELI_CAM_SCAN_PED_SUCCESS', 0, 1 },
    { a_0._f1DE, 'COP_HELI_CAM_SCAN_PED_FAILURE', 0, 1 },
    { a_0._f1DF, 'COP_HELI_CAM_BLEEP_TOO_FAR', 0, 1 },
    { a_0._f1F4, 'CONTINUOUS_SLIDER', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { a_0._f2C[a_1/*1*/], 'SAFE_DOOR_CLOSE', 'SAFE_CRACK_SOUNDSET', 1 },
    { a_0._f2C[a_1/*1*/], 'SAFE_DOOR_OPEN', 'SAFE_CRACK_SOUNDSET', 1 },
    { a_0._f2C[a_1/*1*/], 'TUMBLER_PIN_FALL', 'SAFE_CRACK_SOUNDSET', 1 },
    { a_0._f2C[a_1/*1*/], 'TUMBLER_PIN_FALL_FINAL', 'SAFE_CRACK_SOUNDSET', 1 },
    { a_0._f2C[a_1/*1*/], 'TUMBLER_RESET', 'SAFE_CRACK_SOUNDSET', 1 },
    { a_0._f2C[a_1/*1*/], 'TUMBLER_TURN', 'SAFE_CRACK_SOUNDSET', 1 },
    { a_0._f4D6, 'Hit_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { a_0._f4D7, 'Camera_Move_Loop', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { a_0._f4D8, 'Hit_Out', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { a_0._f5AF, 'Change_Cam', 'MP_CCTV_SOUNDSET', 1 },
    { a_0._f8, 'Background', 'MP_CCTV_SOUNDSET', 1 },
    { a_0._f9, 'Change_Cam', 'MP_CCTV_SOUNDSET', 1 },
    { a_0._fC, 'CHOP_CAM_A', 0, 1 },
    { a_0._fC, 'CHOP_CAM_B', 0, 1 },
    { a_0._fC, 'CHOP_CAM_C', 0, 1 },
    { a_0._fC4, 'COP_HELI_CAM_ZOOM', 0, 1 },
    { a_0._fC5, 'COP_HELI_CAM_TURN', 0, 1 },
    { a_0._fC6, 'COP_HELI_CAM_BLEEP', 0, 1 },
    { a_0._fC7, 'COP_HELI_CAM_BACKGROUND', 0, 1 },
    { a_0._fC8, 'COP_HELI_CAM_SCAN_PED_LOOP', 0, 1 },
    { a_0._fC9, 'COP_HELI_CAM_SCAN_PED_SUCCESS', 0, 1 },
    { a_0._fCA, 'COP_HELI_CAM_SCAN_PED_FAILURE', 0, 1 },
    { a_0._fCB, 'COP_HELI_CAM_BLEEP_TOO_FAR', 0, 1 },
    { a_0._fD, 'Background', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { a_0._fD, 'Remote_Sniper_Rifle_Zoom', 0, 1 },
    { a_0._fE, 'Remote_Sniper_Rifle_Move', 0, 1 },
    { a_0._fF, 'HACKING_MOVE_CURSOR', 0, 1 },
    { a_0._fF, 'Trail_Custom', 'DLC_HEIST_HACKING_SNAKE_SOUNDS', 1 },
    { a_1, 'LOOP', v_4, 1 },
    { a_1, a_0, a_7, 1 },
    { a_2._f1191, 'SLIPSTREAM_MASTER', 0, 1 },
    { a_2._f2EA, 'Return_To_Vehicle_Timer', 'GTAO_FM_Events_Soundset', 0 },
    { a_3, 'Timer_10s', 'GTAO_FM_Events_Soundset', 0 },
    { a_4._fA, 'TIME_LAPSE_MASTER', 0, 1 },
    { g_163E2._f12, 'TextHit', 'MissionFailedSounds', 1 },
    { g_163E2._f13, 'Bed', 'MissionFailedSounds', 1 },
    { g_258071._f11D0, '10S', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_1088, 'Altitude_Warning', 'EXILE_1', 1 },
    { l_10A, 'TIME_LAPSE_MASTER', 0, 1 },
    { l_111, 'SLIPSTREAM_MASTER', 0, 1 },
    { l_1153[a_0/*10*/]._f8, 'DISTANT_DOG_BARK', 'CAR_STEAL_2_SOUNDSET', 1 },
    { l_128E, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_1330, 'In', 'SHORT_PLAYER_SWITCH_SOUND_SET', 1 },
    { l_154, 'Altitude_Warning', 'EXILE_1', 1 },
    { l_15E, 'WIND', 'CONSTRUCTION_ACCIDENT_1_SOUNDS', 1 },
    { l_160B, 'Elevation_Loop', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { l_160B, 'Move_Loop', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { l_160B, 'Rotate_Loop', 'DLC_Dmod_Prop_Editor_Sounds', 0 },
    { l_1796, 'Generic_Alarm_Electronic_01', 0, 1 },
    { l_1805, 'UW_Ambience', 0, 1 },
    { l_1806, 'UW_Rebreather', 0, 1 },
    { l_1807, 'FBI_05_RAID_BREATH', 0, 1 },
    { l_1906, 'Background', 'MP_CCTV_SOUNDSET', 0 },
    { l_1907, 'Pan', 'MP_CCTV_SOUNDSET', 0 },
    { l_1908, 'Zoom', 'MP_CCTV_SOUNDSET', 0 },
    { l_1909, 'Change_Cam', 'MP_CCTV_SOUNDSET', 0 },
    { l_1A4A, 'In', 'SHORT_PLAYER_SWITCH_SOUND_SET', 1 },
    { l_1C67, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_1CB9, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_1D8E, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_1EA, 'PICKUP_WEAPON_BALL', 'HUD_FRONTEND_WEAPONS_PICKUPS_SOUNDSET', 1 },
    { l_1ED, '10s', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_1EE, 'Pickup_Briefcase', 'GTAO_Magnate_Boss_Modes_Soundset', 0 },
    { l_1FBC, 'CLOSING', 'MP_PROPERTIES_ELEVATOR_DOORS', 1 },
    { l_1FBC, 'OPENING', 'MP_PROPERTIES_ELEVATOR_DOORS', 1 },
    { l_206, 'DOOR_BUZZ', 'MP_PLAYER_APARTMENT', 1 },
    { l_208, 'NO', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { l_208, 'QUIT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { l_208, 'YES', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { l_22CB, 'Hit_Out', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_22CC, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_256D, 'Grab_Chute_Foley', 'DLC_Pilot_Chase_Parachute_Sounds', 1 },
    { l_25FB, 'Generic_Alarm_Fire_Electronic', 0, 1 },
    { l_26ED, 'Pull_Out', 'Phone_SoundSet_Franklin', 1 },
    { l_2711, 'OPENED', 'DOOR_GARAGE', 0 },
    { l_2711, 'OPENING', 'DOOR_GARAGE', 0 },
    { l_288E, 'Thernal_Vision_Loop', 'APT_BvS_Soundset', 0 },
    { l_2E1, 'FBI_02_SNATCH_AND_GRAB_AMB_HELI', 0, 1 },
    { l_2EF, 'Pickup_Briefcase', 'GTAO_Magnate_Boss_Modes_Soundset', 0 },
    { l_2F0, 'Blip_Pickup', 'GTAO_Magnate_Boss_Modes_Soundset', 0 },
    { l_3AA, 'Altitude_Warning', 'EXILE_1', 1 },
    { l_3AA, 'Generic_Alarm_Fire_Electronic', 0, 1 },
    { l_3C[0/*1*/], 'HACKING_COUNTDOWN_IP_FIND', 0, 1 },
    { l_3C[1/*1*/], 'HACKING_COUNTDOWN_CRACK_PASS', 0, 1 },
    { l_40[0/*1*/], 'HACKING_COUNTDOWN_IP_FIND', 0, 1 },
    { l_40[1/*1*/], 'HACKING_COUNTDOWN_CRACK_PASS', 0, 1 },
    { l_45E, 'RAMPAGE_TIMER_COUNTDOWN_LOOP_3_MIN_MASTER', 0, 1 },
    { l_45E, 'RAMPAGE_TIMER_COUNTDOWN_LOOP_MASTER', 0, 1 },
    { l_51, l_4F, l_50, 0 },
    { l_512[0/*3*/]._f1, l_512[0/*3*/], 'FAMILY_5_SOUNDS', 1 },
    { l_512[1/*3*/]._f1, l_512[1/*3*/], 'FAMILY_5_SOUNDS', 1 },
    { l_512[2/*3*/]._f1, l_512[2/*3*/], 'FAMILY_5_SOUNDS', 1 },
    { l_57, 'Background_Loop', 'CB_RADIO_SFX', 1 },
    { l_581, '1st_Person_Transition', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_581, 'Hit_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_581, 'HIT_OUT', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_581, 'TIME_LAPSE_MASTER', 0, 1 },
    { l_582, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_5E2, 'EMP', 'DLC_HALLOWEEN_FVJ_Sounds', 0 },
    { l_5E2, 'EMP_Blast', 'DLC_HEISTS_BIOLAB_FINALE_SOUNDS', 0 },
    { l_5E3, '10S', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_5E3, '5S', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_5E3, 'Timer_10s', 'DLC_TG_Dinner_Sounds', 0 },
    { l_5E3, 'Timer_5s', 'DLC_TG_Dinner_Sounds', 0 },
    { l_5E6, 'SLIPSTREAM_MASTER', 0, 0 },
    { l_5ECB, 'Out_of_Bounds', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_5F59, 'OOB_Timer_Dynamic', 'GTAO_FM_Events_Soundset', 0 },
    { l_60F._f26, 'LIMIT', 'DLC_APT_YACHT_DOOR_SOUNDS', 1 },
    { l_60F._f26, 'LIMIT', 'GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS', 1 },
    { l_60F._f26, 'PUSH', 'DLC_APT_YACHT_DOOR_SOUNDS', 1 },
    { l_60F._f26, 'PUSH', 'GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS', 1 },
    { l_60F._f26, 'WOODEN_DOOR_OPEN_NO_HANDLE_AT', 0, 1 },
    { l_61, 'CONTINUOUS_SLIDER', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 1 },
    { l_6A, 'Dial_and_Remote_Ring', &g_3842, 1 },
    { l_6A, 'Remote_Engaged', &g_3842, 1 },
    { l_6A, 'Remote_Ring', &g_3842, 1 },
    { l_6B, 'Camera_Zoom', 'Phone_SoundSet_Glasses_Cam', 1 },
    { l_6C6, 'DOOR_BUZZ', 'MP_PLAYER_APARTMENT', 1 },
    { l_6D, 'Camera_Shoot', 'Phone_SoundSet_Glasses_Cam', 1 },
    { l_6E, 'Background_Sound', 'Phone_SoundSet_Glasses_Cam', 1 },
    { l_70, 'Camera_Zoom', &g_3842, 1 },
    { l_755, 'uw_ambience', 0, 1 },
    { l_77[0/*1*/], 'HACKING_COUNTDOWN_IP_FIND', 0, 1 },
    { l_77[1/*1*/], 'HACKING_COUNTDOWN_CRACK_PASS', 0, 1 },
    { l_7BA, 'ROBBERY_MONEY_TOTAL', 'HUD_FRONTEND_CUSTOM_SOUNDSET', 1 },
    { l_7F, '10s', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_88, 'Out_of_Bounds', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_88[v_3/*1*/], 'Pin_Movement', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 1 },
    { l_89, '5s', 'MP_MISSION_COUNTDOWN_SOUNDSET', 0 },
    { l_8C[v_3/*1*/], 'Pin_Movement', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 1 },
    { l_93D, 'ZOOM', 'PAPARAZZO_02_SOUNDSETS', 1 },
    { l_98A, 'Phone_Generic_Key_02', 'HUD_MINIGAME_SOUNDSET', 1 },
    { l_98A, 'Phone_Generic_Key_03', 'HUD_MINIGAME_SOUNDSET', 1 },
    { l_9B6, 'all', 'SHORT_PLAYER_SWITCH_SOUND_SET', 1 },
    { l_A74, 'Change_Station_Loud', 'Radio_Soundset', 1 },
    { l_AD1._fA, 'TRAFFIC_CONTROL_BG_NOISE', 'BIG_SCORE_3A_SOUNDS', 1 },
    { l_AD1._fB, 'TRAFFIC_CONTROL_CHANGE_CAM', 'BIG_SCORE_3A_SOUNDS', 1 },
    { l_AD1._fC, 'TRAFFIC_CONTROL_TOGGLE_LIGHT', 'BIG_SCORE_3A_SOUNDS', 1 },
    { l_B1, 'VARIABLE_COUNTDOWN_CLOCK_wp', 0, 1 },
    { l_B67, 'ROBBERY_MONEY_TOTAL', 'HUD_FRONTEND_CUSTOM_SOUNDSET', 1 },
    { l_BAC, 'FINDING_VIRUS', 'LESTER1A_SOUNDS', 1 },
    { l_BB0[a_0/*3*/], a_1, 0, 1 },
    { l_BE3, 'OOB_Timer_Dynamic', 'GTAO_FM_Events_Soundset', 0 },
    { l_C3[v_3/*1*/], 'Pin_Movement', 'DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS', 1 },
    { l_C7D, 'UW_Ambience', 0, 1 },
    { l_C8A, 'Short_Transition_In', 'PLAYER_SWITCH_CUSTOM_SOUNDSET', 1 },
    { l_C93, 'Trevor_4_747_TV', 0, 1 },
    { l_CBB, 'FBI_04_HEAT_C4_DOORS', 0, 1 },
    { l_D8A, 'Camera_Hum', 'BIG_SCORE_SETUP_SOUNDS', 1 },
    { l_D8B, 'Camera_Zoom', 'BIG_SCORE_SETUP_SOUNDS', 1 },
    { l_DF1, '10_SEC_WARNING', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { l_E03, 'out', 'SHORT_PLAYER_SWITCH_SOUND_SET', 1 },
    { l_EC._f29, 'LIMIT', 'GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS', 1 },
    { l_EC._f29, 'LIMIT', 'GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS', 1 },
    { l_EC._f29, 'PUSH', 'GTAO_APT_DOOR_DOWNSTAIRS_GLASS_SOUNDS', 1 },
    { l_EC._f29, 'PUSH', 'GTAO_APT_DOOR_DOWNSTAIRS_WOOD_SOUNDS', 1 },
    { l_EC._f29, 'WOODEN_DOOR_OPEN_NO_HANDLE_AT', 0, 1 },
    { l_ECE, 'All', 'SHORT_PLAYER_SWITCH_SOUND_SET', 1 },
    { l_EE[0/*1*/], 'SwitchRedWarning', 'SPECIAL_ABILITY_SOUNDSET', 0 },
    { l_EE[1/*1*/], 'SwitchWhiteWarning', 'SPECIAL_ABILITY_SOUNDSET', 0 },
    { l_F44[3/*1*/], 'Heli_Crash', 'FBI_HEIST_FINALE_CHOPPER', 1 },
    { l_F62, 'Found_Target', 'POLICE_CHOPPER_CAM_SOUNDS', 1 },
    { l_F62, 'Lost_Target', 'POLICE_CHOPPER_CAM_SOUNDS', 1 },
    { l_F62, 'Microphone', 'POLICE_CHOPPER_CAM_SOUNDS', 1 },
    { sub_2a3bd(a_1), 'TIMER_STOP_MASTER', 0, 1 },
    { sub_2a3bd(a_5), 'TIMER_STOP_MASTER', 0, 1 },
    { v_115, 'GARAGE_DOOR_SCRIPTED_CLOSE', 0, 1 },
    { v_2, 'GARAGE_DOOR_SCRIPTED_CLOSE', 0, 1 },
    { v_2, 'GARAGE_DOOR_SCRIPTED_OPEN', 0, 1 },
    { v_2, 'SIGN_DESTROYED', 'HUD_AWARDS', 1 },
    { v_24, 'Remote_Enemy_Enter_Line', 'GTAO_FM_Cross_The_Line_Soundset', 0 },
    { v_24, 'Remote_Friendly_Enter_Line', 'GTAO_FM_Cross_The_Line_Soundset', 0 },
    { v_3, 'Lose_1st', 'GTAO_Magnate_Boss_Modes_Soundset', 0 },
    { v_4, 'Enter_1st', 'GTAO_Magnate_Boss_Modes_Soundset', 0 },
    { v_5, 'CHECKPOINT_UNDER_THE_BRIDGE', 'HUD_MINI_GAME_SOUNDSET', 1 },
    { v_56, 'GARAGE_DOOR_SCRIPTED_CLOSE', 0, 1 },
    { v_7, 'Near_Miss_Counter', 'GTAO_FM_Events_Soundset', 0 },
    { v_9, 'Goon_Paid_Large', 'GTAO_Boss_Goons_FM_Soundset', 0 },
    { v_A, 'COLLECTED', 'HUD_AWARDS', 1 },
    { v_A, 'PEYOTE_COMPLETED', 'HUD_AWARDS', 1 },
    --]]
    { -1, '10_SEC_WARNING', 'HUD_MINI_GAME_SOUNDSET', 1 },
}

local sounds = {
    { -1, 'CANCEL', 'HUD_MINI_GAME_SOUNDSET', 0, 0, 1},
    --{ -1, 'CANCEL', sub_82c23(), 0, 0, 1},
    { -1, 'CHARACTER_CHANGE_CHARACTER_01_MASTER', 0, 0, 0, 0},
    { -1, 'CHARACTER_CHANGE_UP_MASTER', 0, 0, 0, 1},
    --{ -1, 'NAV_UP_DOWN', sub_82c23(), 0, 0, 1},
    { -1, 'SELECT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', 0, 0, 1},
    { -1, 'SELECT', 'HUD_MINI_GAME_SOUNDSET', 0, 0, 1},
    --{ -1, 'SELECT', sub_82c23(), 0, 0, 1},
    { -1, 'slow', 'SHORT_PLAYER_SWITCH_SOUND_SET', 0, 0, 1},
    { -1, 'Take_Picture', 'MUGSHOT_CHARACTER_CREATION_SOUNDS', 0, 0, 1},
    { -1, 'Virus_Eradicated', 'LESTER1A_SOUNDS', 0, 0, 1},
    { -1, 'Zoom_In', 'MUGSHOT_CHARACTER_CREATION_SOUNDS', 0, 0, 1},
    { -1, 'Zoom_Out', 'MUGSHOT_CHARACTER_CREATION_SOUNDS', 0, 0, 1},

    --[[
    { g_42DE._f69, 'CHARACTER_CHANGE_DPAD_DOWN_MASTER', 0, 0, 0, 0},
    { g_42DE._f69, 'CHARACTER_CHANGE_DPAD_DOWN_MP_MASTER', 0, 0, 0, 0},
    { g_42DE._f6B, 'CHARACTER_CHANGE_DOWN_MASTER', 0, 0, 0, 1},
    { g_42DE._f6D, 'All', 'SHORT_PLAYER_SWITCH_SOUND_SET', 0, 0, 1},
    { g_42DE._f6D, 'CHARACTER_CHANGE_SKY_MASTER', 0, 0, 0, 1},
    { l_208, 'CANCEL', 'HUD_MINI_GAME_SOUNDSET', 0, 0, 1},
    { l_208, 'NAV_UP_DOWN', 'HUD_MINI_GAME_SOUNDSET', 0, 0, 1},
    { l_208, 'SELECT', 'HUD_MINI_GAME_SOUNDSET', 0, 0, 1},
    { l_61, 'ent_amb_elec_crackle', 0, 0, 0, 1},
    { l_62, 'spl_stun_npc_master', 0, 0, 0, 1},
    { l_E60, 'Frontend_Beast_Frozen_Screen_Loop', 'FM_Events_Sasquatch_Sounds', 0, 0, 0},
    { v_18, 'Garage_Open', 'CAR_STEAL_2_SOUNDSET', 0, 0, 1},
    --]]
}

Citizen.CreateThread(function()
    while not loaded do
        Citizen.Wait(1000)
        SendNUIMessage({
            action = 'populateTable',
            content = json.encode(soundsFrontend)
        })
        nativeCalled = 'FRONTEND'
        loaded = true
    end

    while true do
        if isVisible then
            -- Disable camera pan and tilt
            DisableControlAction(0, 1, true)
            DisableControlAction(0, 2, true)
        end
        Citizen.Wait(10)
    end
end)

function setVisible(show)
    SetNuiFocus(show, show)
    SendNUIMessage({
        action = 'setVisible',
        show = show
    })
    isVisible = show
end

RegisterNUICallback('close', function(data, cb)
    setVisible(false)
end)

RegisterNUICallback('changeNative', function(data, cb)
    nativeCalled = data['native']
    if nativeCalled == 'FRONTEND' then
        SendNUIMessage({
            action = 'populateTable',
            content = json.encode(soundsFrontend)
        })
    elseif nativeCalled == 'SOUND' then
        SendNUIMessage({
            action = 'populateTable',
            content = json.encode(sounds)
        })
    end
end)

RegisterNUICallback('play', function(data, cb)
    local index = tonumber(data['index'])

    if nativeCalled == 'FRONTEND' then
        PlaySoundFrontend(soundsFrontend[index][1], soundsFrontend[index][2], soundsFrontend[index][3], soundsFrontend[index][4])
    elseif nativeCalled == 'SOUND' then
        PlaySound(sounds[index][1], sounds[index][2], sounds[index][3], sounds[index][4], sounds[index][5], sounds[index][6])
    end
end)

RegisterCommand('nativesounds', function()
    if not isVisible then
        setVisible(true)
    end
end)